In [297]:
import numpy as np
import dask.array as da
from pymks.fmks.correlations import *
from pymks.datasets import make_cahn_hilliard


In [298]:
import numpy as np
from pymks.fmks.bases import legendre
from sklearn.pipeline import Pipeline


In [299]:
n_states = 3
domain = [-1, 1]
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
reducer = PCA(n_components=3)
linker = LogisticRegression()


In [300]:
HomogenizationPipeline=Pipeline(steps=[
    ("discretize",LegendreTransformer(n_state=3, min_=-1.0, max_=1.0) ),
    ('Correlations',TwoPointcorrelation(boundary="periodic", cutoff=42, correlations=[1,1])),
    ('flatten', FlattenTransformer()),  
    ('reducer',reducer),
    ('connector',linker)
])


In [301]:
X0, X1 = make_cahn_hilliard(n_samples=50)
y0 = np.zeros(X0.shape[0])
y1 = np.ones(X1.shape[0])
X = np.concatenate((X0, X1))
y = np.concatenate((y0, y1))

y.shape

(100,)

In [302]:
HomogenizationPipeline.fit(X,y)

ValueError: Found input variables with inconsistent numbers of samples: [85, 100]

In [303]:
X0_test, X1_test = make_cahn_hilliard(n_samples=3)


In [304]:
y1_test = HomogenizationPipeline.predict(X1_test)
y0_test = HomogenizationPipeline.predict(X0_test)
print(y1_test)
print(y0_test)

NotFittedError: This LogisticRegression instance is not fitted yet

In [305]:
Xn=LegendreTransformer(n_state=3, min_=-1.0, max_=1.0).transform(X)
Xn.shape


(100, 21, 21, 3)

In [306]:
Xn=TwoPointcorrelation(boundary="periodic", cutoff=None, correlations=[1,1]).transform(Xn)
Xn.shape

(100, 21, 21)

In [307]:
Xn3=FlattenTransformer().transform(Xn)
Xn3.shape

(100, 441)

In [308]:
Xn4=reducer.fit_transform(Xn3)


In [309]:
mm=linker.fit(Xn4,y)

In [310]:
X0_test, X1_test = make_cahn_hilliard(n_samples=3)


In [311]:
X0_test=LegendreTransformer(n_state=3, min_=-1.0, max_=1.0).transform(X0_test)
X0_test.shape

(3, 21, 21, 3)

In [312]:
X0_test=TwoPointcorrelation(boundary="periodic", cutoff=42, correlations=[1,1]).transform(X0_test)

In [313]:
X0_test.shape

(3, 21, 21)

In [314]:
X0_test

array([[[-4.44633777e-02,  1.85612981e-02,  1.14788446e-02, ...,
         -4.09794473e-02, -1.31280829e-02, -1.81747210e-02],
        [-5.10342059e-02,  2.82880898e-03, -9.43960334e-03, ...,
          3.51803262e-02, -5.49298493e-03,  5.87344510e-02],
        [-3.71436212e-03,  2.65434562e-02, -3.62102060e-02, ...,
          1.26140200e-02, -2.44926588e-02,  1.22358841e-02],
        ...,
        [ 1.22358841e-02, -2.44926588e-02,  1.26140200e-02, ...,
         -3.62102060e-02,  2.65434562e-02, -3.71436212e-03],
        [ 5.87344510e-02, -5.49298493e-03,  3.51803262e-02, ...,
         -9.43960334e-03,  2.82880898e-03, -5.10342059e-02],
        [-1.81747210e-02, -1.31280829e-02, -4.09794473e-02, ...,
          1.14788446e-02,  1.85612981e-02, -4.44633777e-02]],

       [[ 3.12790677e-02,  2.45743862e-02,  1.10686115e-02, ...,
         -2.85505343e-02, -7.14115324e-03, -4.66923696e-02],
        [-2.77342311e-04,  1.31033506e-02,  4.42521807e-02, ...,
         -1.93181412e-02,  7.12810914e

In [315]:
X0_test, X1_test = make_cahn_hilliard(n_samples=3)


In [316]:
X0_test.shape

(3, 21, 21)

In [317]:
y0_test = HomogenizationPipeline.predict(X0_test)

In [318]:
from pymks.fmks.bases.legendre import *

In [319]:
aaa=LegendreTransformer(n_state=2, min_=-1.0, max_=1.0).transform(X)

In [320]:
y0_test

array([0., 0., 0.])

In [321]:
y1_test = HomogenizationPipeline.predict(X1_test)

In [322]:
y1_test

array([1., 1., 1.])