In [2]:

import numpy as np
n_states = 3
domain = [-1, 1]


In [6]:
from pymks.bases import LegendreBasis
leg_basis = LegendreBasis(n_states=n_states, domain=domain)
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from pymks.mks_homogenization_model import MKSHomogenizationModel

In [7]:
reducer = PCA(n_components=3)
linker = LogisticRegression()
model = MKSHomogenizationModel(basis=leg_basis, dimension_reducer=reducer, property_linker=linker)
from pymks.datasets import make_cahn_hilliard

In [8]:
X0, X1 = make_cahn_hilliard(n_samples=50)
y0 = np.zeros(X0.shape[0])
y1 = np.ones(X1.shape[0])

In [9]:
X = np.concatenate((X0, X1))

In [10]:
y = np.concatenate((y0, y1))

In [2]:

import matplotlib.pyplot as plt


plt.imshow(X0[45]);
plt.colorbar()
plt.show()



NameError: name 'X0' is not defined

In [26]:
X0.shape

(50, 21, 21)

In [32]:
X.shape

(100, 21, 21)

In [33]:
model.fit(X, y)

In [59]:
X0_test, X1_test = make_cahn_hilliard(n_samples=3)

In [60]:
y0_test = model.predict(X0_test)

In [62]:
y1_test = model.predict(X1_test)

In [52]:
assert np.allclose(y0_test, [0, 0, 0])

In [53]:
assert np.allclose(y1_test, [1, 1, 1])

In [54]:
X0_test.shape

(3, 21, 21)

In [55]:
y0_test

array([0., 0., 0.])

In [56]:
y1_test

array([1., 1., 1.])

In [61]:
y0_test

array([0., 0., 0.])

In [63]:
y1_test

array([1., 1., 1.])

In [64]:
# What this test does is basically does a regression between inital step for the Cahn hillar case and converged case
# which is not really q good homogenization example (I think) X0 is basically inital concentration field and X1 is basically strain response field





In [65]:
np.allclose(y0_test, [0, 0, 0])

True

In [66]:
np.allclose(y1_test, [1, 1, 1])

True

In [72]:
"""
Let's first start with using the microstructure and effective
        properties.
"""

import numpy as np
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from pymks.bases import PrimitiveBasis
from pymks.stats import correlate


In [73]:
reducer = PCA(n_components=2)
linker = LinearRegression()
prim_basis = PrimitiveBasis(n_states=2, domain=[0, 1])
correlations = [(0, 0), (1, 1), (0, 1)]
model = MKSHomogenizationModel(prim_basis,dimension_reducer=reducer, property_linker=linker,correlations=correlations)

In [74]:
np.random.seed(99)
X = np.random.randint(2, size=(3, 15))
y = np.array([1, 2, 3])
model.fit(X, y)
X_stats = correlate(X, prim_basis)
X_reshaped = X_stats.reshape((X_stats.shape[0], -1))
X_pca = reducer.fit_transform(X_reshaped - np.mean(X_reshaped,axis=1)[:, None])

In [75]:
assert np.allclose(model.reduced_fit_data, X_pca)

In [ ]:
X_reshaped/shape