In [1]:
from pymks.fmks.correaltions_newAPI_Berkay import *


In [2]:
    >>> import dask.array as da
    >>> x_data = np.asarray([[[1, 1, 0],
    ...                       [0, 0, 1],
    ...                       [1, 1, 0]]])
    >>> chunks = x_data.shape
    >>> x_data = da.from_array(x_data, chunks=chunks)
    >>> f_data = auto_correlation(x_data)
    >>> gg = [[[3/9, 2/9, 3/9],
    ...        [2/9, 5/9, 2/9],
    ...        [3/9, 2/9, 3/9]]]
    >>> assert np.allclose(f_data.compute(), gg)

Berkay


In [3]:
f_data.compute()

array([[[0.33333333, 0.22222222, 0.33333333],
        [0.22222222, 0.55555556, 0.22222222],
        [0.33333333, 0.22222222, 0.33333333]]])

In [4]:
Two_point_stats(boundary="periodic",corrtype="cross",args0=x_data,args1=x_data-1).compute()

Berkay


array([[[-2.22222222e-01, -3.33333333e-01, -2.22222222e-01],
        [-3.33333333e-01,  2.63163976e-16, -3.33333333e-01],
        [-2.22222222e-01, -3.33333333e-01, -2.22222222e-01]]])

In [18]:
from sklearn.pipeline import Pipeline
xdata=np.expand_dims(x_data,3)
xdata2=np.expand_dims(1-x_data,3)

xdata.shape
xdata=np.concatenate((xdata,xdata2),axis=3)


In [21]:
bl=Pipeline(steps=[
    ('Correlations',TwoPointcorrelation(boundary="periodic", corrtype="cross", cutoff=None,correlations=[1,0]))
    ])
            

In [22]:
bl.transform(xdata)

Berkay


array([[[ 2.22222222e-01,  3.33333333e-01,  2.22222222e-01],
        [ 3.33333333e-01, -2.63163976e-16,  3.33333333e-01],
        [ 2.22222222e-01,  3.33333333e-01,  2.22222222e-01]]])

In [25]:
FlattenTransformer().transform(np.random.rand(2,21)).shape

(2, 21)

In [26]:
data = np.arange(24).reshape((3, 2, 4))

In [27]:
data.shape

(3, 2, 4)

In [28]:
FlattenTransformer().transform(data)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [30]:
data.shape

(3, 2, 4)

In [31]:
data.reshape(data.shape[0], -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [36]:
from pymks.fmks.localization import flatten
data = np.arange(50).reshape((2, 5, 5))
flatten(data).shape

(2, 25)

In [37]:
FlattenTransformer().transform(data)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])