In [1]:
from pymks.mks_homogenization_model import *

In [2]:
        >>> import numpy as np
        >>> from sklearn.decomposition import PCA
        >>> from sklearn.linear_model import LinearRegression
        >>> from pymks.bases import PrimitiveBasis
        >>> from pymks.stats import correlate

        >>> reducer = PCA(n_components=2)
        >>> linker = LinearRegression()
        >>> prim_basis = PrimitiveBasis(n_states=2, domain=[0, 1])
        >>> correlations = [(0, 0), (1, 1), (0, 1)]
        >>> model = MKSHomogenizationModel(prim_basis,
        ...                                dimension_reducer=reducer,
        ...                                property_linker=linker,
        ...                                correlations=correlations)
        >>> np.random.seed(99)
        >>> X = np.random.randint(2, size=(3, 15))
        >>> y = np.array([1, 2, 3])
        >>> model.fit(X, y)
        >>> X_stats = correlate(X, prim_basis)
        >>> X_reshaped = X_stats.reshape((X_stats.shape[0], -1))
        >>> X_pca = reducer.fit_transform(X_reshaped - np.mean(X_reshaped,
        ...                               axis=1)[:, None])
        >>> assert np.allclose(model.reduced_fit_data, X_pca)
# This Basically checks if PCA works


(0, 1)
(0,)
((0, 1, 0), (0, 1, 1))


In [3]:
X.shape

(3, 15)

In [4]:
prim_basis.discretize(X)[0,:,1]

array([1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1.])

In [5]:
X[0,:]

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1])

In [6]:
model.reduced_fit_data

array([[-0.44593102, -0.27448737],
       [ 0.75160018, -0.03641466],
       [-0.30566916,  0.31090204]])

In [7]:
X_pca

array([[-0.44593102, -0.27448737],
       [ 0.75160018, -0.03641466],
       [-0.30566916,  0.31090204]])

In [14]:
from pymks.stats import _auto_correlations,_cross_correlations

In [15]:
    >>> l = _auto_correlations(np.arange(3))
    >>> assert l == ((0, 1, 2), (0, 1, 2))

In [16]:
    >>> l = _cross_correlations(np.arange(3))
    >>> assert l == ((0, 0, 1), (1, 2, 2))

In [11]:
    >>> from pymks import PrimitiveBasis
    >>> prim_basis = PrimitiveBasis(2, [0, 1])
    >>>
    >>> np.random.seed(0)
    >>> X = np.random.randint(2, size=(1, 3))
    >>> X_corr = correlate(X, prim_basis)
    >>> X_result = np.array([[0, 0.5, 0],
    ...                      [1 / 3., 2 / 3., 0],
    ...                      [0, 0.5, 0.5]])
    >>> assert np.allclose(X_corr, X_result)

(0, 1)
(0,)
((0, 1, 0), (0, 1, 1))


In [12]:
X

array([[0, 1, 1]])