In [1]:
    >>> from pymks.datasets import make_microstructure
    >>> X = make_microstructure(n_samples=4, size=(13, 13), grain_size=(3, 3))


In [6]:
X.shape
import numpy as np
from pymks.stats import correlate

In [7]:
    >>> from pymks import PrimitiveBasis
    >>> prim_basis = PrimitiveBasis(2, [0, 1])
    >>>
    >>> np.random.seed(0)
    >>> X = np.random.randint(2, size=(1, 3))
    >>> X_corr = correlate(X, prim_basis)
    >>> X_result = np.array([[0, 0.5, 0],
    ...                      [1 / 3., 2 / 3., 0],
    ...                      [0, 0.5, 0.5]])

In [11]:
type(prim_basis)

pymks.bases.primitive.PrimitiveBasis

In [22]:
    >>> X = np.array([[[1, 1, 0],
    ...                [1, 0 ,2],
    ...                [0, 1, 0]]])

In [23]:
    >>> prim_basis = PrimitiveBasis(n_states=3)


In [28]:
aa=prim_basis.discretize(X)

In [48]:
aa[0, :, :, 0]

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])

In [49]:
aa[0, :, :, 1]

array([[1., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [50]:
aa[0, :, :, 2]

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

TypeError: 'numpy.ndarray' object is not callable

In [39]:
    >>> from pymks import PrimitiveBasis
    >>> prim_basis = PrimitiveBasis(2, [0, 1])
    >>>
    >>> np.random.seed(0)
    >>> X = np.random.randint(2, size=(1, 3))
    >>> X_corr = correlate(X, prim_basis)
    >>> X_result = np.array([[0, 0.5, 0],
    ...                      [1 / 3., 2 / 3., 0],
    ...                      [0, 0.5, 0.5]])
    >>> assert np.allclose(X_corr, X_result)

In [40]:
X

array([[0, 1, 1]])

In [41]:
prim_basis.discretize(X)

array([[[1., 0.],
        [0., 1.],
        [0., 1.]]])

In [44]:
X_corr

array([[[ 0.00000000e+00,  5.00000000e-01, -1.27046992e-16],
        [ 3.33333333e-01,  6.66666667e-01, -1.48029737e-16],
        [ 0.00000000e+00,  5.00000000e-01,  5.00000000e-01]]])

In [45]:
from pymks.stats import _auto_correlations
_auto_correlations(X)

((array([0, 1, 1]),), (array([0, 1, 1]),))

In [52]:
a=[(0, 0), (0, 2), (0, 4)] 

In [54]:
a[0]

(0, 0)